# Generated by Django 3.1.6 on 2023-09-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rack',
            old_name='rack',
            new_name='rack_ip',
        ),
    ]
